### ISSUE TITLE
execute  ./build_external.sh iOS  error

### ISSUE THREAD

**Issue by k214k** [alibaba/CicadaPlayer#265]
**Describe the bug**
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [curl] Error 1
make[1]: *** [install-recursive] Error 1
make: *** [install-recursive] Error 1

**To Reproduce**
execute  ./build_external.sh iOS

**Desktop (please complete the following information):**
 - OS:mac

**Comment by pingkai** [comment]
please seek actions iOS CI
