### ISSUE TITLE
Android设备播放多音轨ts文件，无音频输出。对比Android中MediaPlayer通用API，缺失一些重要接口

### ISSUE THREAD

**Issue by cysyy** [alibaba/CicadaPlayer#278]
单音轨文件播放正常，有声音输出

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by pingkai** [comment]
close了？是无此问题吗？目前CIcadaPlayer主要的使用场景还是网络播放，并未对本地的多音轨文件进行测试

**Comment by cysyy** [comment]
刚写一行，习惯性按ctrl+enter，自动提交了。。刚刚试了从网络播放多音轨TS流还是无音频输出
