### ISSUE TITLE
mac osx 系统上执行到./genxcodeproj.sh这里报错

### ISSUE THREAD

**Issue by freddiezhao** [alibaba/CicadaPlayer#320]
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
System is unknown to cmake, create:
Platform/iOS to use this system, please send your config file to cmake@www.cmake.org so it can be added to cmake
CMake Error at CMakeLists.txt:3 (project):
  No CMAKE_C_COMPILER could be found.

CMake Error at CMakeLists.txt:3 (project):
  No CMAKE_CXX_COMPILER could be found.

**Comment by pingkai** [comment]
cmake 的版本是多少

**Comment by pingkai** [comment]
cmake版本需要3.14以及以上才行

**Comment by freddiezhao** [comment]
感谢回答,问题解决了,确实需要升级 cmake
