### ISSUE TITLE
Can not open hls hevc master playlist https://bitmovin-a.akamaihd.net/content/dataset/multi-codec/hevc/stream_fmp4.m3u8

### ISSUE THREAD

**Issue by minhtoantm** [alibaba/CicadaPlayer#329]
**Describe the bug**
I tried on iOS, simulator iPhone 11 Pro Max with hls: https://bitmovin-a.akamaihd.net/content/dataset/multi-codec/hevc/stream_fmp4.m3u8
And can not play this link.
Can to check it? I have attached log file.
[hls_hevc_msaterPlaylist.txt](https://github.com/alibaba/CicadaPlayer/files/4867500/hls_hevc_msaterPlaylist.txt)

Thank you.

**Smartphone (please complete the following information):**
 - Device: simulator iPhone 11 pro Max
 - OS: 13.5

**Comment by pingkai** [comment]
please use develop branch to retry

**Comment by minhtoantm** [comment]
I switched to develop branch, video can be played, but when it is so hard to change "video track".
It show loading many times, a not smooth .
Can you check it?
Thank you.

**Comment by pingkai** [comment]
check your network condition  and the link speed to server

**Comment by minhtoantm** [comment]
When I use default branch (release/0.1), Video is very smooth.
Can you check it again?
Thank you.

**Comment by pingkai** [comment]
Your origin issue is not the default branch can't play the  https://bitmovin-a.akamaihd.net/content/dataset/multi-codec/hevc/stream_fmp4.m3u8  stream？

**Comment by minhtoantm** [comment]
I very sorry. Default branch (release/0.1) can not play https://bitmovin-a.akamaihd.net/content/dataset/multi-codec/hevc/stream_fmp4.m3u8

"develop" branch can play, but not smooth and switch track is hard because loading show many times.


And you tell me:
> check your network condition and the link speed to server

I using safari, it play ok, so my network condition is OK.

**Comment by pingkai** [comment]
> When I use default branch (release/0.1), Video is very smooth.
> Can you check it again?
> Thank you.

which video ？not the stream_fmp4.m3u8？

**Comment by minhtoantm** [comment]
Video is mean stream: https://bitmovin-a.akamaihd.net/content/dataset/multi-codec/hevc/stream_fmp4.m3u8
Sorry for miss understand

**Comment by pingkai** [comment]
> Video is mean stream: https://bitmovin-a.akamaihd.net/content/dataset/multi-codec/hevc/stream_fmp4.m3u8
> Sorry for miss understand

You mean the default branch (release/0.1) can play the  stream: https://bitmovin-a.akamaihd.net/content/dataset/multi-codec/hevc/stream_fmp4.m3u8?

**Comment by minhtoantm** [comment]
No.
Default branch (release/0.1) can not play https://bitmovin-a.akamaihd.net/content/dataset/multi-codec/hevc/stream_fmp4.m3u8

Develop branch can play, but not smooth.

**Comment by pingkai** [comment]
> No.
> Default branch (release/0.1) can not play https://bitmovin-a.akamaihd.net/content/dataset/multi-codec/hevc/stream_fmp4.m3u8
> 
> Develop branch can play, but not smooth.

And ... What this

>When I use default branch (release/0.1), Video is very smooth.
>Can you check it again?

**Comment by minhtoantm** [comment]
> > No.
> > Default branch (release/0.1) can not play https://bitmovin-a.akamaihd.net/content/dataset/multi-codec/hevc/stream_fmp4.m3u8
> > Develop branch can play, but not smooth.
> 
> And ... What this
> 
> > When I use default branch (release/0.1), Video is very smooth.
> > Can you check it again?

This is my mistake, I check by safari, video is smooth.
Not default branch.
Sorry about that.

**Comment by pingkai** [comment]
I see，
 Safari Can't switch bandwidth manual，CicadaPlayer don't keep the video smooth in manual switch，it do switch asap，please use 
```c++
player->SelectTrack(-1);
```
to enable auto switch when you want a smooth switch

**Comment by minhtoantm** [comment]
Thank you very much.

**Comment by pingkai** [comment]
Could I close the issue？

**Comment by minhtoantm** [comment]
Yes, I closed it.
Thank you very much.
