### ISSUE TITLE
Question about DRM support

### ISSUE THREAD

**Issue by ragotiteb** [alibaba/CicadaPlayer#490]
Hi

This project looks quite interesting and promising with regards to unified playback. 

An important piece of information i have not been able to obtain and that is an important concern for me is the DRM support. What (if any) DRMs are supported and on which platforms? Is there any resource on the web where i can see what the plans are, and examples of DRM-protected content playback is supported?

**Comment by pingkai** [comment]
Hello ragotiteb,
the CicadaPlayer have integrated the EXOPlayer to support Widevine  on Android, you can use the CicadaPlayer api to invoke the EXOPlayer to play a Widevine DRM on Android. And we have started to implement the Widevine DRM playback in native C/C++ code, it will be released on next month in the version release/0.3.

And CicadaPlayer have already integrated the AVPlayer on Apple platform,  you can use the CicadaPlayer api to invoke it to play a FairePlay DRM video, but  as you know we can't implement it by ourselves, we must use the AVPlayer.

And you can generate a hls stream with the multiDRM use shaka packager, you can play it on Android and Apple platforms both.

Both of the demo are available on our demo.

Thanks.

**Comment by ragotiteb** [comment]
I see, thanks for the answer

A couple of follow-up questions: 
1.does this mean then that , in the case of iOS, the underlying players used is in fact AVPlayer? By looking at the compilation instructions i was wondering if the core playback for iOS was ffplay . I take it then that it is not? Or is it for non-DRM protected content?
2.Does Cicada player support RTMP on iOS? If so, i take it that this would be perhaps a ffplay-based implementation

The reason to probe for these details is that our application needs to perform some adjustments in some core aspects of the video playback, which we have achieved in Android by modifying exoplayer, but now we are looking for a good base to do the same for iOS.  

Thanks again!

**Comment by pingkai** [comment]
Hi

1. we use AVPlayer only to play fairplay DRM content, because fairplay DRM is a private drm owned by Apple. The core playback is not ffplay, we use ffmpeg for some modules implemention， eg. bit stream demuxer， software decoder，and some filters in framework used by player core, and the player core not know the existence of ffmpeg.

2. Cicada player support rtmp on all platform, the rtmp demxuer was implemented use ffmpeg, but I don't think the rtmp is better than http+flv.

**Comment by ragotiteb** [comment]
I see, thanks once again for the responses!
