### ISSUE TITLE
Drop OpenGL ES on iOS

### ISSUE THREAD

**Issue by pingkai** [alibaba/CicadaPlayer#516]
OpenGLES is deprecated and is not available when building for Mac Catalyst.

https://developer.apple.com/forums/thread/126450

We can use AVSamplebufferDisplayLayer to display yuv, and use Metal to implement the panoramic video

**Comment by foobra** [comment]
why, opengl es can use in any platform.  
write once shader, run anywhere.
iOS: EAGL 3.0
Android: EGL 1.4/1.5
mac/linux/win : angle
