### ISSUE TITLE
播放视频容易卡顿

### ISSUE THREAD

**Issue by xuqingquan1995** [alibaba/CicadaPlayer#526]
在同一个网络环境下，播放同一个m3u8资源，使用这个播放器会更加容易遇到卡顿的情况，缓存速度也更慢，开始播放时间也会比较久

**Comment by pingkai** [comment]
贴个地址？或者提供一个log？

**Comment by xuqingquan1995** [comment]
https://tudou.com-l-tudou.com/20180427/10460_a6259634/index.m3u8

特别是在弱网环境下对比测试会非常明显，对比的播放器是GSYVideoPlayer

**Comment by xuqingquan1995** [comment]
对于m3u8的ts加载，有没有使用多线程呢？

**Comment by pingkai** [comment]
我这里播放不卡，加入钉钉群吧

莫企邀请你加入钉钉群聊CicadaPlayer，点击进入查看详情 https://h5.dingtalk.com/circle/healthCheckin.html?corpId=ding05a17e71e273ef01706c2bdf30687d5e&8312258=71fc7a9&cbdbhh=qwertyuiop&origin=1

**Comment by xuqingquan1995** [comment]
好像不能直接加入？

**Comment by pingkai** [comment]
可以的，填下联系方式就行了，钉钉

**Comment by xuqingquan1995** [comment]
提示该群为组织内部群，请先联系管理员加入该组织

**Comment by pingkai** [comment]
哦哦，不好意思，搞错了，用这个，这个链接和二维码在我们的主页readme上也是有的。

https://h5.dingtalk.com/invite-page/index.html?bizSource=____source____&corpId=ding42c495ce0dcfdb7f35c2f4657eb6378f&inviterUid=B8D63ADF200A8E9DFF4BBDCA828801C7&encodeDeptId=FE36B0936DFD1AC591E7FE61FE0552A6
