### ISSUE TITLE
xcframework? 

### ISSUE THREAD

**Issue by azureplus** [alibaba/CicadaPlayer#637]
support xcframework?

**Comment by pingkai** [comment]
not support for now until we drop the usage of OpenGLES which will be finished on release 0.4

**Comment by DSPerson** [comment]
> not support for now until we drop the usage of OpenGLES which will be finished on release 0.4

还有计划么？

**Comment by pingkai** [comment]
我们正在准备发布catalyst平台，catalyst和xcframework有一定关系，不过目前这个需求不是很强烈，目前也没有人希望我们提供xcframework，发布xcframework后，我们要维护xcframework和framework两套sdk，会比较麻烦；所以暂时没有计划

**Comment by DSPerson** [comment]
谢谢。但是我估计以苹果的尿性 啥时候真的吧framework干掉

**Comment by pingkai** [comment]
苹果要真干掉framework的话，也就好了，我们就不用维护framework了，直接出xcframework，就是现在这种非强制的情况下，比较麻烦，因为我们要面对上万的开发这，多一个问题，会造成很大的支持成本
