### ISSUE TITLE
why return -1 instead of INT64_MIN or 0?

### ISSUE THREAD

**Issue by rancpine** [alibaba/CicadaPlayer#646]
https://github.com/alibaba/CicadaPlayer/blob/7c31f6cfe5c23fd86c82b842ccc060be603e3abc/platform/Apple/source/CicadaPlayer.mm#L934

it seems that SystemReferClock use INT64_MIN to check the return value of a refer clock(SystemReferClock::isMasterValid).

while af_clock is initialized by 0.

**Comment by pingkai** [comment]
o , I think it's a bug, pr welcome!!
