### ISSUE TITLE
Can't compile windows on win10

### ISSUE THREAD

**Issue by zhlgh603** [alibaba/CicadaPlayer#675]
按文档compile windows on win10 use visual studio 2017操作到3.build cmdline
执行CicadaPlayer\cmdline\msvc_build\build_win.bat

出现如下错误：
1>E:\workspace\CicadaPlayer\framework\utils\ffmpeg_utils.c(8): fatal error C1083: 无法打开包括文件: “libavcodec/h264_parse.h”: No such file or directory
1>已完成生成项目“framework_utils.vcxproj”的操作 - 失败。

**Comment by pingkai** [comment]
明显是头文件没找到，检测一下ffmpeg的源码路径和install路径

**Comment by zhlgh603** [comment]
> 明显是头文件没找到，检测一下ffmpeg的源码路径和install路径

![ffmpeg_utils](https://user-images.githubusercontent.com/11733727/109766716-831eaf00-7c31-11eb-8a5b-23b8c9713420.PNG)

SHA-1: e7fcfec013a3f14a6f94002e5d9d9f3d61f96ffe

* feat(wideVine): add WideVine support

这个提交引入了更多的头文件，导致按文档操作无法编译

**Comment by pingkai** [comment]
你需要ffmpeg的源码，并且把源码放到对应的目录下才行，这里依赖了ffmpeg的内部头文件，后面我们依赖ffmpeg内部头文件应该会越来越多
