### ISSUE TITLE
能否支持从应用层主动送入视频和和视频进行播放

### ISSUE THREAD

**Issue by llatecomers** [alibaba/CicadaPlayer#677]
ffmpeg不支持第三方私有协议拉流，能否提供接口由外部主动送入视频和音频数据进行解码和渲染。

**Comment by I-m-SuperMan** [comment]
我觉得有两种方式考虑：
1. 直接走协议代理：将私有协议通过http代理，转为标准的http的地址。这样就可以无缝对接ffmpeg。
2. 实现播放器的IDataSource接口，实现私有协议的open/read/seek/close等操作。

**Comment by pingkai** [comment]
> 我觉得有两种方式考虑：
> 
> 1. 直接走协议代理：将私有协议通过http代理，转为标准的http的地址。这样就可以无缝对接ffmpeg。
> 2. 实现播放器的IDataSource接口，实现私有协议的open/read/seek/close等操作。

@I-m-SuperMan 咱们的播放器不是有bitstreamsource接口吗？直接用这个就比较简单了吧？
