### ISSUE TITLE
Sometimes CicadaEventCompletion is not called

### ISSUE THREAD

**Issue by isaacroldan** [alibaba/CicadaPlayer#686]
**Describe the bug**
I'm testing an RTMP streaming, when I stop the streaming I expect the `CicadaEventCompletion` event to be triggered. But sometimes (1 out of 3 maybe), it doesn't. Appears to happen specially if the streaming has been running for some time.

**To Reproduce**
1. Open a RTMP streaming
2. Wait some time (1 min maybe)
3. Stop the streaming from the source (in my case, I'm using VOYSYS to emit to a local server)

**Expected behavior**
`CicadaEventCompletion` should be triggered but instead `CicadaEventLoadingStart` and `CicadaEventLoadingEnd` are triggered multiple times.

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro
 - OS: iOS 14.5

**Additional context**
This has been tested in different RTMP streams, servers, devices and by different people.
I've tried to look into Cicada code to see where the issue might be, with no luck :/

**Comment by pingkai** [comment]
I think the palyer can't get the eos event form rtmp stream, you can try it use ffplay

**Comment by isaacroldan** [comment]
Using ffplay the stream always stops, but I noticed something:
- When it works fine in Cicada, it works in FFPlay too (the stream is closed immediately)
- When it doesn't work in Cicada, FFPlay takes a few seconds before closing the stream (keeps the image frozen for about 5 seconds before deciding the stream has ended).

So, to summarize, in Cicada sometimes I never get the Completed event, but in FFPlay I always get this (for the same stream, testing at the same time):
```
HandleInvoke, server invoking <onStatus>
HandleInvoke, onStatus: NetStream.Play.Stop
Invoking deleteStream
Got Play.Complete or Play.Stop from server. Assuming stream is complete
```

**Comment by isaacroldan** [comment]
Found a workaround (and the way ffplay handles this too I think).

After a timeout an error is thrown and I use that error to detect that the stream has ended, that's way FFPlay takes 5 second to close the stream.

Thanks!
