### ISSUE TITLE
请问如何编译iOS真机

### ISSUE THREAD

**Issue by DSPerson** [alibaba/CicadaPlayer#689]
# 按照教程编译出来的framework 只包含arm 模拟器的，求教如何修改脚本

**Comment by pingkai** [comment]
请参考
https://github.com/alibaba/CicadaPlayer/blob/release/0.3/.github/workflows/iOS.yml

**Comment by DSPerson** [comment]
> 请参考 https://github.com/alibaba/CicadaPlayer/blob/release/0.3/.github/workflows/iOS.yml
