### ISSUE TITLE
CicadaPlayer音视频同步算法

### ISSUE THREAD

**Issue by zhangjp0405** [alibaba/CicadaPlayer#693]
你好，请问在framework\render\video\vsync\timedVSync.cpp文件里timedVSync::timedThread()函数的
int delay = mPeriod - (mClock.get()) % mPeriod;
af_usleep(delay);
为什么音视频同步是这两条语句，不应该是音频的pts-视频的pts差值大于200或小于10这样来判断的吗

**Comment by pingkai** [comment]
This is Vsync, NOT AVSync

**Comment by zhangjp0405** [comment]
为什么要af_usleep(delay)；每个视频帧之间进行休眠一次

**Comment by pingkai** [comment]
这里是模拟了一个vsync信号，正常每个系统里面都有，比如iOS的displaylink；因为一些兼容性问题，平台相关的接口我们暂时没有用

**Comment by zhangjp0405** [comment]
你好，Ping Kai
向你请教下，有没开源的音视频采集代码(采集桌面画面或打开摄像头采集，同时采集音频)可以推荐




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Ping ***@***.***&gt;; 
发送时间: 2022年1月17日(星期一) 中午11:59
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [alibaba/CicadaPlayer] CicadaPlayer音视频同步算法 (Issue #693)





 
这里是模拟了一个vsync信号，正常每个系统里面都有，比如iOS的displaylink；因为一些兼容性问题，平台相关的接口我们暂时没有用
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by pingkai** [comment]
ffmpeg本身就支持吧，场景复杂的话可以看看obs
