### ISSUE TITLE
iOS build   fatal: 不是 git 仓库（或者任何父目录）：.git

### ISSUE THREAD

**Issue by LiuKaoji** [alibaba/CicadaPlayer#697]
**Describe the bug**
按照顺序构建iOS版本 无法编译成功

编译环境
MacOS  12.1 (21C52)
Xcode 13.2.1 (13C100)
MacBook Air M1芯片 
使用rosetta环境 oh-my-zsh

./build_external.sh [iOS](url)
控制台输出见附件
[build.log](https://github.com/alibaba/CicadaPlayer/files/7983424/build.log)

**Comment by pingkai** [comment]
看样子已经 编译完了，直接打开Xcode工程试试吧，建议使用bash环境
