### ISSUE TITLE
seekto android 12正常 android 11 每次定位的帧不一样

### ISSUE THREAD

**Issue by Kastrcn** [alibaba/CicadaPlayer#699]
seekto android 12正常 android 11 每次定位的帧不一样

**Comment by I-m-SuperMan** [comment]
已经定位解决了。已经同步到github上。

**Comment by pingkai** [comment]
https://github.com/alibaba/CicadaPlayer/commit/fbaab456cb177dcaaf064a11bb6512dd969d933d 应该是这个吧
