### ISSUE TITLE
Bug:   Playing not correctly with a complex master playlist m3u8 

### ISSUE THREAD

**Issue by Romantic-LiXuefeng** [alibaba/CicadaPlayer#7]
## System info
Using Android CicadaPlayer
### Issue description
When playing with Apple master playlist advanced (TS) url, [https://devstreaming-cdn.apple.com/videos/streaming/examples/img_bipbop_adv_example_ts/master.m3u8](url),  the player only play audio and subtitle stream at first,   About 10s later， the video stream begins to play, there isn't in AVSync.   We test the url with `ExoPlayer`, it plays well. 

### Reproduction steps
Replace the input url with [https://devstreaming-cdn.apple.com/videos/streaming/examples/img_bipbop_adv_example_ts/master.m3u8](url). The issue can be reproduced.

**Comment by pingkai** [comment]
Thanks for feedback, the hls features was not be supported fully by now, we will try to fix it later.

**Comment by pingkai** [comment]
packet audio is not support for now

**Comment by pingkai** [comment]
packed aac id3 was supported at https://github.com/pingkai/CicadaPlayer/tree/feature/fmp4, it will be merged on v0.2.0

**Comment by pingkai** [comment]
have merged to develop branch
