### ISSUE TITLE
执行./build_external.sh macOS 报错

### ISSUE THREAD

**Issue by ShengQiangLiu** [alibaba/CicadaPlayer#700]
external % ./build_external.sh macOS

TOP_DIR is /Users/lsq/github/CicadaPlayer/external
mkdir: external: File exists
user_sources is ../player_git_source_list.sh
apply ../player_git_source_list.sh
fatal: destination path 'ffmpeg' already exists and is not an empty directory.
fatal: destination path 'openssl' already exists and is not an empty directory.
fatal: destination path 'curl' already exists and is not an empty directory.
fatal: destination path 'libxml2' already exists and is not an empty directory.
Applying: chore(win32): fix not find openssl 1.1.1
error: patch failed: configure:6355
error: configure: patch does not apply
Patch failed at 0001 chore(win32): fix not find openssl 1.1.1
hint: Use 'git am --show-current-patch' to see the failed patch
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".
patch error, may be patched
Applying: chore(libavformat): exoport some functions
error: patch failed: libavformat/libavformat.v:1
error: libavformat/libavformat.v: patch does not apply
Patch failed at 0001 chore(libavformat): exoport some functions
hint: Use 'git am --show-current-patch' to see the failed patch
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".
patch error, may be patched
Applying: chore: fix Linux build
error: patch failed: configure:6357
error: configure: patch does not apply
Patch failed at 0001 chore: fix Linux build
hint: Use 'git am --show-current-patch' to see the failed patch
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".
patch error, may be patched
Applying: chore: disable libdav1d check
error: patch failed: configure:6196
error: configure: patch does not apply
Patch failed at 0001 chore: disable libdav1d check
hint: Use 'git am --show-current-patch' to see the failed patch
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".
patch error, may be patched
Applying: flv: add extensions for H.265/HEVC
error: patch failed: libavformat/flv.h:110
error: libavformat/flv.h: patch does not apply
error: patch failed: libavformat/flvdec.c:37
error: libavformat/flvdec.c: patch does not apply
error: patch failed: libavformat/flvenc.c:34
error: libavformat/flvenc.c: patch does not apply
Patch failed at 0001 flv: add extensions for H.265/HEVC
hint: Use 'git am --show-current-patch' to see the failed patch
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".
patch error, may be patched
Applying: build(libavformat): compile avc.c and hevc.c default
error: patch failed: libavformat/Makefile:23
error: libavformat/Makefile: patch does not apply
Patch failed at 0001 build(libavformat): compile avc.c and hevc.c default
hint: Use 'git am --show-current-patch' to see the failed patch
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".
patch error, may be patched
Applying: avformat/flvdec: add aliyun extend auio codec id
error: patch failed: libavformat/flv.h:99
error: libavformat/flv.h: patch does not apply
error: patch failed: libavformat/flvdec.c:189
error: libavformat/flvdec.c: patch does not apply
Patch failed at 0001 avformat/flvdec: add aliyun extend auio codec id
hint: Use 'git am --show-current-patch' to see the failed patch
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".
patch error, may be patched
Applying: chore(configure): xml2 use check lib
error: patch failed: configure:6318
error: configure: patch does not apply
Patch failed at 0001 chore(configure): xml2 use check lib
hint: Use 'git am --show-current-patch' to see the failed patch
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".
patch error, may be patched
Applying: disable check libtool
error: patch failed: autogen.sh:21
error: autogen.sh: patch does not apply
Patch failed at 0001 disable check libtool
hint: Use 'git am --show-current-patch' to see the failed patch
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".
patch error, may be patched
Applying: curl-functions.m4: remove inappropriate AC_REQUIRE
error: patch failed: m4/curl-functions.m4:7289
error: m4/curl-functions.m4: patch does not apply
Patch failed at 0001 curl-functions.m4: remove inappropriate AC_REQUIRE
hint: Use 'git am --show-current-patch' to see the failed patch
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".
patch error, may be patched
TOP_DIR is /Users/lsq/github/CicadaPlayer/external
boost source not found
cares source not found
native build for Darwin
Configuring OpenSSL version 1.1.1g (0x1010107fL) for darwin64-x86_64-cc
Using os-specific seed configuration
Creating configdata.pm
Creating Makefile

**Comment by ShengQiangLiu** [comment]
Undefined symbols for architecture x86_64:
  "_ASN1_STRING_get0_data", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_ASN1_STRING_length", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_ASN1_STRING_print", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_ASN1_STRING_to_UTF8", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_ASN1_STRING_type", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_ASN1_TIME_print", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_BIO_ctrl", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
      _x509_name_oneline in libcurl.a(libcurl_la-openssl.o)
      _pubkey_show in libcurl.a(libcurl_la-openssl.o)
  "_BIO_f_ssl", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_BIO_free", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
      _x509_name_oneline in libcurl.a(libcurl_la-openssl.o)
  "_BIO_new", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
      _x509_name_oneline in libcurl.a(libcurl_la-openssl.o)
  "_BIO_new_mem_buf", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_BIO_printf", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_BIO_puts", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_BIO_s_file", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_BIO_s_mem", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
      _x509_name_oneline in libcurl.a(libcurl_la-openssl.o)
  "_BN_num_bits", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_BN_print", referenced from:
      _pubkey_show in libcurl.a(libcurl_la-openssl.o)
  "_CRYPTO_free", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_CRYPTO_get_ex_new_index", referenced from:
      _ossl_get_ssl_data_index in libcurl.a(libcurl_la-openssl.o)
      _ossl_get_ssl_conn_index in libcurl.a(libcurl_la-openssl.o)
      _ossl_get_ssl_sockindex_index in libcurl.a(libcurl_la-openssl.o)
      _ossl_get_proxy_index in libcurl.a(libcurl_la-openssl.o)
  "_CRYPTO_malloc", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_DES_ecb_encrypt", referenced from:
      _Curl_ntlm_core_lm_resp in libcurl.a(libcurl_la-curl_ntlm_core.o)
      _Curl_ntlm_core_mk_lm_hash in libcurl.a(libcurl_la-curl_ntlm_core.o)
  "_DES_set_key", referenced from:
      _setup_des_key in libcurl.a(libcurl_la-curl_ntlm_core.o)
  "_DES_set_odd_parity", referenced from:
      _setup_des_key in libcurl.a(libcurl_la-curl_ntlm_core.o)
  "_DH_get0_key", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_DH_get0_pqg", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_DSA_get0_key", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_DSA_get0_pqg", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_ENGINE_by_id", referenced from:
      _ossl_set_engine in libcurl.a(libcurl_la-openssl.o)
  "_ENGINE_ctrl", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_ENGINE_ctrl_cmd", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_ENGINE_finish", referenced from:
      _ossl_close_all in libcurl.a(libcurl_la-openssl.o)
      _ossl_set_engine in libcurl.a(libcurl_la-openssl.o)
  "_ENGINE_free", referenced from:
      _ossl_close_all in libcurl.a(libcurl_la-openssl.o)
      _ossl_set_engine in libcurl.a(libcurl_la-openssl.o)
  "_ENGINE_get_first", referenced from:
      _ossl_engines_list in libcurl.a(libcurl_la-openssl.o)
  "_ENGINE_get_id", referenced from:
      _ossl_set_engine_default in libcurl.a(libcurl_la-openssl.o)
      _ossl_engines_list in libcurl.a(libcurl_la-openssl.o)
  "_ENGINE_get_next", referenced from:
      _ossl_engines_list in libcurl.a(libcurl_la-openssl.o)
  "_ENGINE_init", referenced from:
      _ossl_set_engine in libcurl.a(libcurl_la-openssl.o)
  "_ENGINE_load_private_key", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_ENGINE_set_default", referenced from:
      _ossl_set_engine_default in libcurl.a(libcurl_la-openssl.o)
  "_ERR_clear_error", referenced from:
      _ossl_shutdown in libcurl.a(libcurl_la-openssl.o)
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
      _ossl_recv in libcurl.a(libcurl_la-openssl.o)
      _ossl_send in libcurl.a(libcurl_la-openssl.o)
  "_ERR_error_string_n", referenced from:
      _ossl_strerror in libcurl.a(libcurl_la-openssl.o)
  "_ERR_get_error", referenced from:
      _ossl_shutdown in libcurl.a(libcurl_la-openssl.o)
      _ossl_set_engine in libcurl.a(libcurl_la-openssl.o)
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
      _ossl_recv in libcurl.a(libcurl_la-openssl.o)
      _ossl_send in libcurl.a(libcurl_la-openssl.o)
  "_ERR_peek_error", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_ERR_peek_last_error", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_EVP_DigestFinal_ex", referenced from:
      _ossl_sha256sum in libcurl.a(libcurl_la-openssl.o)
  "_EVP_DigestInit", referenced from:
      _ossl_sha256sum in libcurl.a(libcurl_la-openssl.o)
  "_EVP_DigestUpdate", referenced from:
      _ossl_sha256sum in libcurl.a(libcurl_la-openssl.o)
  "_EVP_MD_CTX_free", referenced from:
      _ossl_sha256sum in libcurl.a(libcurl_la-openssl.o)
  "_EVP_MD_CTX_new", referenced from:
      _ossl_sha256sum in libcurl.a(libcurl_la-openssl.o)
  "_EVP_PKEY_copy_parameters", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_EVP_PKEY_free", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_EVP_PKEY_get0_DH", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_EVP_PKEY_get0_DSA", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_EVP_PKEY_get0_RSA", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_EVP_PKEY_get1_RSA", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_EVP_PKEY_id", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_EVP_sha1", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_EVP_sha256", referenced from:
      _ossl_sha256sum in libcurl.a(libcurl_la-openssl.o)
  "_GENERAL_NAMES_free", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_MD4_Final", referenced from:
      _Curl_md4it in libcurl.a(libcurl_la-md4.o)
  "_MD4_Init", referenced from:
      _Curl_md4it in libcurl.a(libcurl_la-md4.o)
  "_MD4_Update", referenced from:
      _Curl_md4it in libcurl.a(libcurl_la-md4.o)
  "_MD5_Final", referenced from:
      _Curl_md5it in libcurl.a(libcurl_la-md5.o)
      _Curl_HMAC_MD5 in libcurl.a(libcurl_la-md5.o)
      _Curl_DIGEST_MD5 in libcurl.a(libcurl_la-md5.o)
  "_MD5_Init", referenced from:
      _Curl_md5it in libcurl.a(libcurl_la-md5.o)
      _Curl_HMAC_MD5 in libcurl.a(libcurl_la-md5.o)
      _Curl_DIGEST_MD5 in libcurl.a(libcurl_la-md5.o)
  "_MD5_Update", referenced from:
      _Curl_md5it in libcurl.a(libcurl_la-md5.o)
      _Curl_HMAC_MD5 in libcurl.a(libcurl_la-md5.o)
      _Curl_DIGEST_MD5 in libcurl.a(libcurl_la-md5.o)
  "_OCSP_BASICRESP_free", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_OCSP_CERTID_free", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_OCSP_RESPONSE_free", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_OCSP_basic_verify", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_OCSP_cert_status_str", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_OCSP_cert_to_id", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_OCSP_check_validity", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_OCSP_crl_reason_str", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_OCSP_resp_find_status", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_OCSP_response_get1_basic", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_OCSP_response_status", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_OCSP_response_status_str", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_OPENSSL_init_ssl", referenced from:
      _ossl_init in libcurl.a(libcurl_la-openssl.o)
  "_OPENSSL_sk_num", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_OPENSSL_sk_pop", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_OPENSSL_sk_pop_free", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_OPENSSL_sk_value", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_OpenSSL_version_num", referenced from:
      _ossl_version in libcurl.a(libcurl_la-openssl.o)
  "_PEM_read_bio_PrivateKey", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_PEM_read_bio_X509", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_PEM_read_bio_X509_AUX", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_PEM_write_bio_X509", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_PKCS12_PBE_add", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_PKCS12_free", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_PKCS12_parse", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_RAND_add", referenced from:
      _ossl_seed in libcurl.a(libcurl_la-openssl.o)
  "_RAND_bytes", referenced from:
      _ossl_random in libcurl.a(libcurl_la-openssl.o)
  "_RAND_file_name", referenced from:
      _ossl_seed in libcurl.a(libcurl_la-openssl.o)
  "_RAND_load_file", referenced from:
      _ossl_seed in libcurl.a(libcurl_la-openssl.o)
  "_RAND_status", referenced from:
      _ossl_random in libcurl.a(libcurl_la-openssl.o)
      _ossl_seed in libcurl.a(libcurl_la-openssl.o)
  "_RSA_flags", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_RSA_free", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_RSA_get0_key", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_SHA256_Final", referenced from:
      _Curl_sha256it in libcurl.a(libcurl_la-sha256.o)
      _Curl_HMAC_SHA256 in libcurl.a(libcurl_la-sha256.o)
  "_SHA256_Init", referenced from:
      _Curl_sha256it in libcurl.a(libcurl_la-sha256.o)
      _Curl_HMAC_SHA256 in libcurl.a(libcurl_la-sha256.o)
  "_SHA256_Update", referenced from:
      _Curl_sha256it in libcurl.a(libcurl_la-sha256.o)
      _Curl_HMAC_SHA256 in libcurl.a(libcurl_la-sha256.o)
  "_SSL_CIPHER_get_name", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_SSL_CTX_add_client_CA", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_SSL_CTX_check_private_key", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_SSL_CTX_ctrl", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_SSL_CTX_free", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
      _ossl_closeone in libcurl.a(libcurl_la-openssl.o)
  "_SSL_CTX_get_cert_store", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_SSL_CTX_load_verify_locations", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_SSL_CTX_new", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_SSL_CTX_sess_set_new_cb", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_SSL_CTX_set_alpn_protos", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_SSL_CTX_set_cipher_list", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_SSL_CTX_set_ciphersuites", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_SSL_CTX_set_default_passwd_cb", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_SSL_CTX_set_default_passwd_cb_userdata", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_SSL_CTX_set_keylog_callback", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_SSL_CTX_set_msg_callback", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_SSL_CTX_set_next_proto_select_cb", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_SSL_CTX_set_options", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_SSL_CTX_set_post_handshake_auth", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_SSL_CTX_set_srp_password", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_SSL_CTX_set_srp_username", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_SSL_CTX_set_verify", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_SSL_CTX_use_PrivateKey", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_SSL_CTX_use_PrivateKey_file", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_SSL_CTX_use_certificate", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_SSL_CTX_use_certificate_chain_file", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_SSL_CTX_use_certificate_file", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_SSL_SESSION_free", referenced from:
      _ossl_session_free in libcurl.a(libcurl_la-openssl.o)
  "_SSL_alert_desc_string_long", referenced from:
      _ossl_trace in libcurl.a(libcurl_la-openssl.o)
  "_SSL_connect", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_SSL_ctrl", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_SSL_free", referenced from:
      _ossl_shutdown in libcurl.a(libcurl_la-openssl.o)
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
      _ossl_closeone in libcurl.a(libcurl_la-openssl.o)
  "_SSL_get0_alpn_selected", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_SSL_get_certificate", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_SSL_get_current_cipher", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_SSL_get_error", referenced from:
      _ossl_shutdown in libcurl.a(libcurl_la-openssl.o)
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
      _ossl_recv in libcurl.a(libcurl_la-openssl.o)
      _ossl_send in libcurl.a(libcurl_la-openssl.o)
  "_SSL_get_ex_data", referenced from:
      _ossl_new_session_cb in libcurl.a(libcurl_la-openssl.o)
  "_SSL_get_peer_cert_chain", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_SSL_get_peer_certificate", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_SSL_get_privatekey", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_SSL_get_shutdown", referenced from:
      _ossl_shutdown in libcurl.a(libcurl_la-openssl.o)
  "_SSL_get_verify_result", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_SSL_get_version", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_SSL_new", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_SSL_pending", referenced from:
      _ossl_data_pending in libcurl.a(libcurl_la-openssl.o)
  "_SSL_read", referenced from:
      _ossl_shutdown in libcurl.a(libcurl_la-openssl.o)
      _ossl_recv in libcurl.a(libcurl_la-openssl.o)
  "_SSL_set_bio", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_SSL_set_connect_state", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
      _ossl_closeone in libcurl.a(libcurl_la-openssl.o)
  "_SSL_set_ex_data", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_SSL_set_fd", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_SSL_set_session", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_SSL_shutdown", referenced from:
      _ossl_closeone in libcurl.a(libcurl_la-openssl.o)
  "_SSL_write", referenced from:
      _ossl_send in libcurl.a(libcurl_la-openssl.o)
  "_TLS_client_method", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_UI_OpenSSL", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
      _ssl_ui_reader in libcurl.a(libcurl_la-openssl.o)
      _ssl_ui_writer in libcurl.a(libcurl_la-openssl.o)
  "_UI_create_method", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_UI_destroy_method", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_UI_get0_user_data", referenced from:
      _ssl_ui_reader in libcurl.a(libcurl_la-openssl.o)
      _ssl_ui_writer in libcurl.a(libcurl_la-openssl.o)
  "_UI_get_input_flags", referenced from:
      _ssl_ui_reader in libcurl.a(libcurl_la-openssl.o)
      _ssl_ui_writer in libcurl.a(libcurl_la-openssl.o)
  "_UI_get_string_type", referenced from:
      _ssl_ui_reader in libcurl.a(libcurl_la-openssl.o)
      _ssl_ui_writer in libcurl.a(libcurl_la-openssl.o)
  "_UI_method_get_closer", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_UI_method_get_opener", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_UI_method_get_reader", referenced from:
      _ssl_ui_reader in libcurl.a(libcurl_la-openssl.o)
  "_UI_method_get_writer", referenced from:
      _ssl_ui_writer in libcurl.a(libcurl_la-openssl.o)
  "_UI_method_set_closer", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_UI_method_set_opener", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_UI_method_set_reader", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_UI_method_set_writer", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_UI_set_result", referenced from:
      _ssl_ui_reader in libcurl.a(libcurl_la-openssl.o)
  "_X509V3_EXT_print", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_X509_EXTENSION_get_data", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_X509_EXTENSION_get_object", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_X509_LOOKUP_file", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_X509_NAME_ENTRY_get_data", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_X509_NAME_get_entry", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_X509_NAME_get_index_by_NID", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_X509_NAME_print_ex", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
      _x509_name_oneline in libcurl.a(libcurl_la-openssl.o)
  "_X509_PUBKEY_get0_param", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_X509_STORE_add_lookup", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_X509_STORE_set_flags", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_X509_check_issued", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_X509_free", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_X509_get0_extensions", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_X509_get0_notAfter", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_X509_get0_notBefore", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_X509_get0_signature", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_X509_get_X509_PUBKEY", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_X509_get_ext_d2i", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_X509_get_issuer_name", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_X509_get_pubkey", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_X509_get_serialNumber", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_X509_get_subject_name", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_X509_get_version", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_X509_load_crl_file", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_X509_verify_cert_error_string", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_d2i_OCSP_RESPONSE", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_d2i_PKCS12_bio", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_d2i_PrivateKey_bio", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_d2i_X509_bio", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_i2a_ASN1_OBJECT", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_i2d_X509_PUBKEY", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_i2t_ASN1_OBJECT", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **

**Comment by ShengQiangLiu** [comment]
MakBookPro13 
macOS Catalina 10.15.6
Xcode 12.2

**Comment by pingkai** [comment]
应该是openssl编译失败了，请参考
https://github.com/alibaba/CicadaPlayer/blob/release/0.4/.github/workflows/macOS.yml
