### ISSUE TITLE
ABR for Apple iOS

### ISSUE THREAD

**Issue by yudinm** [alibaba/CicadaPlayer#714]
In the source code is present AbrManager. In the features, ABR is also declared. But I could not find an interface for working with it in iOS. Are there any options for enabling ABR for iOS?

**Comment by kongjianneu** [comment]
You can call  MediaPlayer::SelectTrack(SELECT_TRACK_VIDEO_AUTO) to enable ABR

**Comment by yudinm** [comment]
> You can call MediaPlayer::SelectTrack(SELECT_TRACK_VIDEO_AUTO) to enable ABR

Thank you. Works perfect.
