### ISSUE TITLE
How to get the decoded frame data (yuv) in CicadaPlayer

### ISSUE THREAD

**Issue by xfirefly** [alibaba/CicadaPlayer#732]
Thanks

**Comment by futan-yj** [comment]
> Thanks

Hi, there's no existing API to get yuv, but the core has implemented, you can reference the bridge example
between  CicadaPlayer.java:
public interface OnVideoRenderedListener{
        void onVideoRendered(long timeMs , long pts);
    }
and MediaPlayer.cpp:
MediaPlayer::SetAudioRenderingCallback.

, to build your own OnRenderFrameCallback and this callback has yuv data.
