### ISSUE TITLE
fatal error: libxml/xmlreader.h: No such file or directory

### ISSUE THREAD

**Issue by laojiang2023** [alibaba/CicadaPlayer#738]
Hello, 

你好，我这边在MacOS上按照你们的compile_Windows.md编译windows的库，执行到下面的命令：
cmake -DCMAKE_TOOLCHAIN_FILE=../cmdline/toolchain.windows.cmake ../
make cicadaPlayer
会报这个错误

Documents/work/mThor/CicadaPlayer/framework/utils/xml/DOMParser.h:9:10: fatal error: libxml/xmlreader.h: No such file or directory
    9 | #include <libxml/xmlreader.h>
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [mediaPlayer.out/framework.out/demuxer/CMakeFiles/demuxer.dir/demuxerPrototype.cpp.obj] Error 1
make[2]: *** [mediaPlayer.out/framework.out/demuxer/CMakeFiles/demuxer.dir/all] Error 2
make[1]: *** [CMakeFiles/cicadaPlayer.dir/rule] Error 2

请问该如何解决，谢谢

**Comment by ehyea** [comment]
请问，这个问题你是怎么解决的呢？
