### ISSUE TITLE
好像此项目已不再更新, 请问是否可用  阿里云播放器SDK(ApsaraVideo Player SDK) 来替换, 保持接口不变

### ISSUE THREAD

**Issue by xfirefly** [alibaba/CicadaPlayer#751]
好像此项目已不再更新, 是否可用  阿里云播放器SDK(ApsaraVideo Player SDK) 来替换, 保持接口不变? 

[ 阿里云播放器SDK(ApsaraVideo Player SDK)  ](https://help.aliyun.com/zh/vod/developer-reference/sdk-overview-and-download?spm=a2c4g.11186623.0.0.1d85477fw71MB6#topic-1959787)

**Comment by NighWish** [comment]
@xfirefly 你替换了吗？这个新的是收费还是免费的？

**Comment by xfirefly** [comment]
> @xfirefly 你替换了吗？这个新的是收费还是免费的？

免费, 但不开源
